server:
  port: 8030
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-customer
          uri: http://localhost:8020
          predicates:
            - Path=/personalAccount/**, /businessAccount/**
